### ISSUE TITLE
Issue with generated manifest id for depot

### ISSUE THREAD

**Issue by NPC-112** [Sak32009/SteamACFGenerator#28]
I've recently come across this project in an attempt to repair and generate 130+ game appmanifest files.

I accidentally only copied my steamapps\common folder but none of the manifests and didn't want to have to select install on each game individually. 

I made a short script to scrape the appids from the games files and run your program for each, and it worked!
But steam says it can't find the manifest file for each. Digging deeper, each game has a manifest ID generated in the acf that doesn't match what steam would generate or what's available on steamdb.info.

Digging _even deeper_ I found that your program is rounding up the last 4 digits of each manifest entry. Every acf file I cross checked with steam generated ones show three zeroes (000) at the end.
Is this caused by steamcmd or the program writing the acf file?

<details>

<summary>the specific part of each acf file that's wrong</summary>

### **The correct manifest is "321655889397364980", but yours output "321655889397365000"**

Generated acf
```
"InstalledDepots"
	{
		"354201"
		{
			"manifest"		"321655889397365000"
			"size"		"244941158"
		}
	}
```
Official Steam acf
```
"InstalledDepots"
	{
		"354201"
		{
			"manifest"		"321655889397364980"
			"size"		"244941158"
		}
	}
```

</details>

<details>

<summary>Generated .acf File</summary>

```
"AppState"
{
	"appid"		"354200"
	"Universe"		"1"
	"LauncherPath"		""
	"name"		"Aberoth"
	"StateFlags"		"4"
	"installdir"		"Aberoth"
	"LastUpdated"		"0"
	"SizeOnDisk"		"244941158"
	"StagingSize"		"0"
	"buildid"		"4529222"
	"LastOwner"		"2009"
	"UpdateResult"		"0"
	"BytesToDownload"		"0"
	"BytesDownloaded"		"0"
	"BytesToStage"		"0"
	"BytesStaged"		"0"
	"TargetBuildID"		"0"
	"AutoUpdateBehavior"		"0"
	"AllowOtherDownloadsWhileRunning"		"0"
	"ScheduledAutoUpdate"		"0"
	"InstalledDepots"
	{
		"354201"
		{
			"manifest"		"321655889397365000"
			"size"		"244941158"
		}
	}
}

```

</details>

<details>

<summary>Steam .acf File</summary>

```
"AppState"
{
	"appid"		"354200"
	"Universe"		"1"
	"LauncherPath"		"C:\\Program Files (x86)\\Steam\\steam.exe"
	"name"		"Aberoth"
	"StateFlags"		"4"
	"installdir"		"Aberoth"
	"LastUpdated"		"1667341532"
	"SizeOnDisk"		"244941158"
	"StagingSize"		"0"
	"buildid"		"4529222"
	"LastOwner"		"76561198049684393"
	"UpdateResult"		"0"
	"BytesToDownload"		"102214688"
	"BytesDownloaded"		"102214688"
	"BytesToStage"		"244941158"
	"BytesStaged"		"244941158"
	"TargetBuildID"		"4529222"
	"AutoUpdateBehavior"		"0"
	"AllowOtherDownloadsWhileRunning"		"0"
	"ScheduledAutoUpdate"		"0"
	"InstalledDepots"
	{
		"354201"
		{
			"manifest"		"321655889397364980"
			"size"		"244941158"
		}
	}
	"UserConfig"
	{
		"language"		"english"
	}
	"MountedConfig"
	{
		"language"		"english"
	}
}
```

</details>

<details>

<summary>Batch script I made to generate the appids from the game folders</summary>

```
@echo off
SETLOCAL EnableDelayedExpansion

@REM delete previous runs files
if exist results.txt del /f /q results.txt
if exist source.txt del /f /q source.txt
@REM Create list of files and directories in current folder and subfolders
dir /s /b > source.txt

@REM Cut out only the lines that point to a steam_appid.txt file
set str2find=steam_appid.txt
findstr /s /i "%str2find%" source.txt && findstr /i "%str2find%" source.txt >> results.txt

@REM Loop through each file, the only text in them should be the number ID.
@REM For each, run generator 
set appid=
for /f "tokens=*" %%f in (results.txt) do (
  echo found: %%f
  set /p appid=<%%f
  steam-acf-generator.exe --appids !appid!
)
exit /b
```
</details>

**Comment by NPC-112** [comment]
Manually ran steamcmd, it outputs the correct manifest. So the problem stems from the acf parser I think.

**Comment by Sak32009** [comment]
Probably the first time I have the honor of reading an excellent description of the bug. Also this has been fixed for https://github.com/Sak32009/GetDLCInfoFromSteamDB as well. Sorry for the late reply.
